### Create a User
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "Fulando de Tal",
  "email": "fulano@mail.com",
  "password": "123456578"
}

### Sign In
POST http://localhost:3001/api/users/sign-in
Content-Type: application/json

{
  "email": "fulano@mail.com",
  "password": "123456578"
}

### Create a Transaction
POST http://localhost:3001/api/transactions
Content-Type: application/json
Authorization: Bearer token

{
  "title": "Gasto no mercado do mês",
  "value": 589.50,
  "type": false
}

### Get Transaction of Id
GET http://localhost:3001/api/transactions/:id

### Get All User Transaction of id
GET http://localhost:3001/api/transactions?page=1&pageSize=10
Authorization: Bearer token

### Delete Transaction of id
DELETE http://localhost:3001/api/transactions/:id
Authorization: Bearer token
### Update Transaction of id
PUT http://localhost:3001/api/transactions/31f9e220-be69-41c5-a7ce-a7d287310634
Content-Type: application/json
Authorization: Bearer token

{
  "type": true
}
