@HOST = localhost
@PORT = 3001
@VERSION = v1
@URL = http://{{HOST}}:{{PORT}}/api/{{VERSION}}
@TOKEN =

### Create a User
POST {{URL}}/users
Content-Type: application/json

{
  "name": "Fulando de Tal",
  "email": "fulano@mail.com",
  "password": "123456578"
}

### Sign In
POST {{URL}}/users/sign-in
Content-Type: application/json

{
  "email": "fulano@mail.com",
  "password": "123456578"
}

### Create a Transaction
POST {{URL}}/transactions
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "title": "Gasto no mercado do mês",
  "value": 589.50,
  "type": false
}

### Get Transaction of Id
GET {{URL}}/transactions/:id
Authorization: Bearer {{TOKEN}}

### Get All User Transaction of id
GET {{URL}}/transactions?page=1
Authorization: Bearer {{TOKEN}}

### Delete Transaction of id
DELETE {{URL}}/transactions/:id
Authorization: Bearer {{TOKEN}}
### Update Transaction of id
PUT {{URL}}/transactions/:id
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "type": true
}
