### Create a User
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "Fulando de Tal",
  "email": "fulano@mail.com",
  "password": "123456578"
}

### Create a Transaction
POST http://localhost:3001/api/transactions
Content-Type: application/json

{
  "userId": "fe8d6d26-1f42-4f41-96b4-ec44c9ee9b9e",
  "title": "Gasto no mercado do mês",
  "value": 589.50,
  "type": false
}

### Get Transaction of Id
GET http://localhost:3001/api/transactions/:id

### Get All User Transaction of id
GET http://localhost:3001/api/transactions/list/:userId
