version: '3.7'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=spending_pad
    volumes:
      - spending_pad_data:/bitami/postgresql
volumes:
  spending_pad_data:
